name: run_tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python-headless pytest numpy 
    - name: test with pytest
      run : |
        pytest ./tests
